package org.hibernate.test.resource2.jdbc.common;

import java.sql.PreparedStatement;
import java.sql.Statement;

import org.hibernate.ScrollMode;
import org.hibernate.engine.jdbc.spi.StatementPreparer;

/**
 * @author Steve Ebersole
 */
public class BasicStatementPreparer implements StatementPreparer {
	@Override
	public Statement createStatement() {
		return null;  //To change body of implemented methods use File | Settings | File Templates.
	}

	@Override
	public PreparedStatement prepareStatement(String sql) {
		return null;  //To change body of implemented methods use File | Settings | File Templates.
	}

	@Override
	public PreparedStatement prepareStatement(String sql, boolean isCallable) {
		return null;  //To change body of implemented methods use File | Settings | File Templates.
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) {
		return null;  //To change body of implemented methods use File | Settings | File Templates.
	}

	@Override
	public PreparedStatement prepareStatement(String sql, String[] columnNames) {
		return null;  //To change body of implemented methods use File | Settings | File Templates.
	}

	@Override
	public PreparedStatement prepareQueryStatement(
			String sql, boolean isCallable, ScrollMode scrollMode) {
		return null;  //To change body of implemented methods use File | Settings | File Templates.
	}
}
